name: Metadata Correction
description: Fix typos or errors in a paper's title, abstract, or author names
title: "[Metadata revision to Anthology ID]: "
labels: ["correction", "metadata"]
assignees:
  - xinru1414
body:
  - type: input
    id: anthology_id
    attributes:
      label: Anthology ID
      placeholder: ex. 2020.acl-1.17 or P19-1017
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: email@example.com
    validations:
      required: true
  - type: input
    id: paper_title
    attributes:
      label: Paper Title Metadata Correction
      description: What is the correct paper title?
      placeholder: "Correct paper title is: "
    validations:
      required: false
  - type: textarea
    id: paper_abstract
    attributes:
      label: Paper Abstract Correction
      description: What is the correct paper abstract?
      placeholder: "Correct paper abstract is: "
    validations:
      required: false
  - type: input
    id: author_name
    attributes:
      label: Author Name Metadata Correction
      description: What is the correct author first name and last name?
      placeholder: "First name:  Last name:  "
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        If you request an author name correction for yourself, please also make sure that your name is correctly entered into Softconf/OpenReview for any future publications, as this is where we obtain the author names from.
  - type: dropdown
    id: correction_type
    attributes:
      label: Metadata Correction Type
      description: What type of metadata correction is this?
      options:
        - label: Paper Title
        - label: Paper Abstrct
        - label: Author Name
    validations:
      required: true
